services:
  hims_postgres:
    networks:
      - app_network
    image: postgres:latest
    container_name: hims_postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hims
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  hims_pgadmin:
    networks:
      - app_network
    image: dpage/pgadmin4
    container_name: hims_pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./db/config.json:/pgadmin4/servers.json
    depends_on:
      hims_postgres:
        condition: service_healthy
networks:
  app_network:
    driver: bridge

volumes:
  db:
