version: '3.8'

services:
  hims_mysql:
    networks:
      - hims_network
    image: mysql:latest
    container_name: hims_mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hims
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: UTC
    command: --default-time-zone='+00:00'
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  hims_phpmyadmin:
    networks:
      - hims_network
    image: phpmyadmin/phpmyadmin
    container_name: hims_phpmyadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PMA_HOST: hims_mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    depends_on:
      hims_mysql:
        condition: service_healthy

networks:
  hims_network:
    driver: bridge

volumes:
  db:
